### ISSUE TITLE
Node-RED -> call service

### ISSUE THREAD

**Issue by AdnWik** [NinDTendo/homeassistant_gradual_volume_control#2]
When I try to call service in Node-RED I get an API error.

debug log:
  sent data : msg :
  object
      domain: "grad_vol"
      service: "set_volume"
  data: object
      volume: 0.5
      duration: 10
      entity_id: "media_player.whole_house"

Is there a way to use "grad_vol" via Node-RED?

**Comment by NinDTendo** [comment]
Unfortunately I have no experience with Node-Red...
what kind of speaker is your `media_player.whole_house` ?
